# Generated by Django 3.1.6 on 2021-04-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyrespondents', to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='respondent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='core.respondent'),
        ),
        migrations.DeleteModel(
            name='UserOrganisation',
        ),
    ]
