# Generated by Django 3.1.6 on 2021-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
