# Generated by Django 3.1.6 on 2021-05-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='avatar-default.png', upload_to='network/'),
        ),
    ]
