# Generated by Django 3.1.6 on 2021-05-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210504_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='rate',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
