# Generated by Django 3.1.6 on 2021-05-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210513_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='post_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='pre_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
