# Generated by Django 3.1.6 on 2021-05-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210505_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='stakeholder_groups',
        ),
        migrations.AddField(
            model_name='survey',
            name='stakeholdergroup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.stakeholdergroup'),
            preserve_default=False,
        ),
    ]
