# Generated by Django 3.1.6 on 2021-04-02 11:56

import core.models.campaign
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customuser_uniquetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('open_survey_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_survey_date', models.DateTimeField(default=core.models.campaign.defaultrespondingwindow)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='method',
            name='organisations',
        ),
        migrations.CreateModel(
            name='EseaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.method')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.method'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.network'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='esea_accounts',
            field=models.ManyToManyField(blank=True, related_name='organisations', through='core.EseaAccount', to='core.Method'),
        ),
    ]
