# Generated by Django 3.1.6 on 2021-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210505_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
