# Generated by Django 3.1.6 on 2021-05-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210514_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='token',
            field=models.CharField(max_length=10),
        ),
    ]
