# Generated by Django 3.1.6 on 2021-06-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210514_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='directindicator',
            name='Datatype',
            field=models.CharField(choices=[('TEXT', 'text'), ('INTEGER', 'integer'), ('DOUBLE', 'double'), ('DATE', 'date'), ('BOOLEAN', 'boolean'), ('SINGLECHOICE', 'singlechoice'), ('MULTIPLECHOICE', 'multiplechoice')], default='TEXT', max_length=50),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='datatype',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('DOUBLE', 'Double'), ('DATE', 'Date'), ('BOOLEAN', 'boolean'), ('SINGLECHOICE', 'singlechoice'), ('MULTIPLECHOICE', 'multiplechoice')], default='TEXT', max_length=100),
        ),
    ]
