# Generated by Django 3.1.6 on 2021-04-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210402_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='A New Campaign', max_length=255),
        ),
        migrations.CreateModel(
            name='IndirectIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('formula', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indirect_indicators', to='core.topic')),
            ],
            options={
                'unique_together': {('name', 'topic')},
            },
        ),
    ]
