# Generated by Django 3.1.6 on 2021-04-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210403_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('esea_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='report', serialize=False, to='core.eseaaccount')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='eseaaccount',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_accounts', to='core.campaign'),
        ),
    ]
