# Generated by Django 3.1.6 on 2021-06-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210605_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directindicator',
            old_name='Datatype',
            new_name='datatype',
        ),
    ]
