# Generated by Django 3.1.6 on 2021-05-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210509_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='Version',
            new_name='version',
        ),
    ]
