# Generated by Django 3.1.6 on 2021-04-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_surveyresponse_esea_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='eseaaccount',
            name='sufficient_responses',
            field=models.BooleanField(default=False),
        ),
    ]
