# Generated by Django 3.1.6 on 2021-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210605_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectindicator',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'Performance'), ('SCORING', 'Scoring')], default='SCORING', max_length=50),
        ),
        migrations.AlterField(
            model_name='indirectindicator',
            name='datatype',
            field=models.CharField(choices=[('TEXT', 'text'), ('INTEGER', 'integer'), ('DOUBLE', 'double'), ('DATE', 'date'), ('BOOLEAN', 'boolean'), ('SINGLECHOICE', 'singlechoice'), ('MULTIPLECHOICE', 'multiplechoice')], default='TEXT', max_length=50),
        ),
    ]
