# Generated by Django 3.1.6 on 2021-05-09 20:34

import core.models.survey
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210509_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='rate',
        ),
        migrations.AddField(
            model_name='indirectindicator',
            name='datatype',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('DOUBLE', 'Double'), ('DATE', 'Date')], default='TEXT', max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='minThreshold',
            field=models.PositiveSmallIntegerField(default=100, null=True, validators=[core.models.survey.validate_max]),
        ),
    ]
