# Generated by Django 3.1.6 on 2021-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210612_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uiComponent',
            field=models.CharField(choices=[('FIELD', 'field'), ('LINE', 'line'), ('TEXTBOX', 'textBox'), ('CHECKBOX', 'checkBox'), ('DROPDOWN', 'dropDown'), ('RADIOBUTTON', 'radioButton')], default='field', max_length=100),
        ),
    ]
