# Generated by Django 3.1.6 on 2021-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_eseaaccount_response_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirectindicator',
            name='key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='indirectindicator',
            unique_together={('key', 'topic')},
        ),
    ]
