# Generated by Django 3.1.6 on 2021-06-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_question_uicomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='post_unit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='pre_unit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
