# Generated by Django 3.1.6 on 2021-04-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210408_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectindicator',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirect_indicators', to='core.topic'),
        ),
    ]
