# Generated by Django 3.1.6 on 2021-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210509_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='minThreshold',
        ),
        migrations.AddField(
            model_name='survey',
            name='closing_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='min_threshold',
            field=models.PositiveSmallIntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='welcome_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
