# Generated by Django 3.1.6 on 2021-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210408_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
