# Generated by Django 3.1.6 on 2021-06-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210621_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirectindicator',
            name='formula',
            field=models.CharField(max_length=511),
        ),
    ]
