# Generated by Django 3.1.6 on 2021-06-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210621_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
