# Generated by Django 3.1.6 on 2021-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210408_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
