# Generated by Django 3.1.6 on 2021-06-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210621_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_indicators', to='core.question'),
        ),
    ]
