# Generated by Django 3.1.6 on 2021-05-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210510_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
