# Generated by Django 3.1.6 on 2021-05-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210510_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='eseaaccount',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
