# Generated by Django 3.1.6 on 2021-06-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210621_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='directindicator',
            name='indicator_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
