# Generated by Django 3.1.6 on 2021-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210413_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, default='organisation/sustainability-circle.png', upload_to='organisation/'),
        ),
    ]
