# Generated by Django 3.1.6 on 2021-06-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_directindicator_indicator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('text', models.CharField(max_length=255)),
                ('direct_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.directindicator')),
            ],
        ),
    ]
