# Generated by Django 3.1.6 on 2021-04-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, default='campaign/campaign-default.png', upload_to='campaign/'),
        ),
    ]
