# Generated by Django 3.1.6 on 2021-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_eseaaccount_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
