# Generated by Django 3.1.6 on 2021-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
