# Generated by Django 3.1.6 on 2021-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_answeroption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='direct_indicator',
        ),
        migrations.AddField(
            model_name='directindicator',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='direct_indicator', to='core.AnswerOption'),
        ),
    ]
