# Generated by Django 3.1.6 on 2021-06-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210621_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('title', models.TextField(blank=True, max_length=1000)),
                ('questions', models.ManyToManyField(related_name='section', to='core.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_indicator', to='core.topic'),
        ),
        migrations.CreateModel(
            name='TextFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fragments', to='core.section')),
            ],
        ),
    ]
