# Generated by Django 3.1.6 on 2021-05-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_directindicator_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='responseType',
            new_name='response_type',
        ),
    ]
