# Generated by Django 3.1.6 on 2021-06-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210622_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.survey'),
        ),
    ]
