# Generated by Django 3.1.6 on 2021-06-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_section_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section'),
        ),
    ]
