# Generated by Django 3.1.6 on 2021-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210622_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directindicator',
            name='options',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='direct_indicator',
            field=models.ManyToManyField(blank=True, related_name='options', to='core.DirectIndicator'),
        ),
    ]
