# Generated by Django 3.1.6 on 2021-06-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210622_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directindicator',
            old_name='indicator_name',
            new_name='name',
        ),
    ]
