# Generated by Django 3.1.6 on 2021-05-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210511_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='image',
            field=models.ImageField(blank=True, default='network/sustainability-circle.png', upload_to='network/'),
        ),
    ]
