# Generated by Django 3.1.6 on 2021-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210623_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('INTEGER', 'INTEGER'), ('DOUBLE', 'DOUBLE'), ('DATE', 'DATE'), ('BOOLEAN', 'BOOLEAN'), ('SINGLECHOICE', 'SINGLECHOICE'), ('MULTIPLECHOICE', 'MULTIPLECHOICE')], default='TEXT', max_length=50),
        ),
    ]
