# Generated by Django 3.1.6 on 2021-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210623_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('DOUBLE', 'Double'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('SINGLECHOICE', 'SingleChoice'), ('MULTIPLECHOICE', 'MultipleChoice')], default='TEXT', max_length=50),
        ),
    ]
