# Generated by Django 3.1.6 on 2021-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210623_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('double', 'Double'), ('date', 'Date'), ('boolean', 'Boolean'), ('singlechoice', 'SingleChoice'), ('multiplechoice', 'MultipleChoice')], default='TEXT', max_length=50),
        ),
    ]
