# Generated by Django 3.1.6 on 2021-06-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210623_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='datatype',
            field=models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Double', 'Double'), ('Date', 'Date'), ('Boolean', 'Boolean'), ('Singlechoice', 'SingleChoice'), ('Multiplechoice', 'MultipleChoice')], default='TEXT', max_length=50),
        ),
    ]
