# Generated by Django 3.1.6 on 2021-06-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210623_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_of_topic', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uiComponent',
            field=models.CharField(choices=[('field', 'field'), ('line', 'line'), ('textbox', 'textBox'), ('checkbox', 'checkBox'), ('dropdown', 'dropDown'), ('radiobutton', 'radioButton')], default='field', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='response_type',
            field=models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], default='SINGLE', max_length=100),
        ),
    ]
