# Generated by Django 3.1.6 on 2021-06-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210626_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='directindicator',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_indicators', to='core.method'),
        ),
    ]
