# Generated by Django 3.1.6 on 2021-06-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_directindicator_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directindicator',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_indicator', to='core.question'),
        ),
    ]
